apiVersion: apps/v1
kind: Deployment
metadata:
    name: priobike-mqtt-authenticator-deployment
spec:
    replicas: {{ .Values.replicas }}
    selector: 
      matchLabels:
        app: priobike-mqtt-authenticator-app
    template:
      metadata: 
        labels: 
          app: priobike-mqtt-authenticator-app
      spec:
        imagePullSecrets:
        - name: regcred

        containers:
        - name: priobike-mqtt-authenticator-container
          image: bikenow.vkw.tu-dresden.de/priobike/priobike-mqtt-authenticator:v1.0
          ports:
          - containerPort: {{ .Values.containerPort }}
          envFrom:
          - configMapRef:
              name: priobike-mqtt-authenticator-config
          - secretRef:
              name: priobike-mqtt-authenticator-secret
