apiVersion: v1
kind: Secret
metadata:
  name: priobike-mqtt-authenticator-secret
data:
  USERNAMES: backend,user
  PASSWORDS: {{ required "A valid .Values.PASSWORDS entry required! (two comma separated passwords. First one for 'backend' user (publish rights) and second one for 'user' user (only subscribe rights))" .Values.PASSWORDS }}