apiVersion: v1
kind: Secret
metadata:
  name: priobike-mqtt-authenticator-secret
data:
  # USERNAMES: backend,user
  USERNAMES: YmFja2VuZCx1c2Vy 
  PASSWORDS: {{ required "A valid .Values.passwords entry required! (two comma separated passwords. First one for 'backend' user (publish rights) and second one for 'user' user (only subscribe rights))" .Values.passwords | b64enc}}
