apiVersion: v1
kind: Service
metadata:
  name: priobike-mqtt-authenticator-service
spec:
  selector:
    app: priobike-mqtt-authenticator-app
  ports:
    - protocol: TCP
      port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}
  type: ClusterIP