apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
data:
  DEFAULT_HOST: {{ required "A valid .Values.defaultHost entry is required!" .Values.defaultHost }}
  IS_HTTPS_ENABLED: "true"
  {{- if .Values.dbDriver }}
  DB_DRIVER: {{ .Values.dbDriver }}
  DB_HOST: |-
    {{ .Values.dbServiceName }}.
    {{- (.Values.global).namespace | default .Values.namespace | required "A valid .Values.namespace or .Values.global.namespace entry is required!" -}}
    .svc.cluster.local
  {{- end }}
  DISABLE_TRACKING: {{ .Values.disableTracking | quote }}
