apiVersion: v1
kind: Secret
metadata:
  name: priobike-shlink-secret
data:
  INITIAL_API_KEY: {{ required "A valid .Values.initialApiKey entry required!" .Values.initialApiKey }}
  DB_NAME: {{ required "A valid .Values.dbName entry required!" .Values.dbName }}
  DB_USER: {{ required "A valid .Values.dbUser entry required!" .Values.dbUser }}
  DB_PASSWORD: {{ required "A valid .Values.dbPassword entry required!" .Values.dbPassword }}
