apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
data:
  INITIAL_API_KEY: {{ required "A valid .Values.initialApiKey entry is required!" .Values.initialApiKey | b64enc }}
  DB_NAME: {{ required "A valid .Values.dbName entry is required!" .Values.dbName | b64enc }}
  DB_USER: {{ required "A valid .Values.dbUser entry is required!" .Values.dbUser | b64enc }}
  DB_PASSWORD: {{ required "A valid .Values.dbPassword entry is required!" .Values.dbPassword | b64enc }}
