apiVersion: v1
kind: Secret
metadata:
  name: priobike-shlink-secret
data:
  INITIAL_API_KEY: {{ required "A valid .Values.initialApiKey entry required!" .Values.initialApiKey | b64enc }}
  DB_NAME: {{ required "A valid .Values.dbName entry required!" .Values.dbName | b64enc }}
  DB_USER: {{ required "A valid .Values.dbUser entry required!" .Values.dbUser | b64enc }}
  DB_PASSWORD: {{ required "A valid .Values.dbPassword entry required!" .Values.dbPassword | b64enc }}
