apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
data:
  persistence_db_username: {{ required "A valid .Values.persistenceDbUsername entry is required!" .Values.persistenceDbUsername | b64enc }}
  persistence_db_password: {{ required "A valid .Values.persistenceDbPassword entry is required!" .Values.persistenceDbPassword | b64enc }}