apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.serviceName }}
spec:
  selector:
    app: {{ .Values.nginx.labels.app }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
