apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
data:
  PREDICTION_MQTT_USERNAME: {{ required "A valid .Values.predictionMqttUsername entry is required!" .Values.predictionMqttUsername | b64enc }}
  PREDICTION_MQTT_PASSWORD: {{ required "A valid .Values.predictionMqttPassword entry is required!" .Values.predictionMqttPassword | b64enc }}
