apiVersion: v1
kind: Service
metadata:
  name: priobike-shlink-guard-service
spec:
  selector:
    app: priobike-shlink-guard-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP