apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.worker.configMapName }}
data:
  DEBUG: {{ .Values.worker.debug | quote }}
  WORKER_MODE: "True"
  MANAGER_HOST: |-
    {{ .Values.manager.serviceName | required "A valid .Values.manager.serviceName entry is required!" -}}
    .
    {{- (.Values.global).namespace | default .Values.namespace | required "A valid .Values.namespace or .Values.global.namespace entry is required!" -}}
    .svc.cluster.local
  APP_URL: {{ .Values.worker.appUrl }}
