apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.worker.secretName }}
data:
  DJANGO_KEY: {{ required "A valid .Values.djangoKey entry is required!" .Values.djangoKey | b64enc }}
  SYNC_KEY: {{ required "A valid .Values.syncKey entry is required!" .Values.syncKey | b64enc }}