apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.worker.serviceName }}
spec:
  selector:
    app: {{ .Values.worker.labels.app }}
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP