apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.worker.headlessServiceName }}
spec:
  selector:
    app: {{ .Values.worker.labels.app }}
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  clusterIP: None
  type: ClusterIP
