apiVersion: v1
kind: Service
metadata:
  name: priobike-privacy-policy-service-service
spec:
  selector:
    app: priobike-privacy-policy-service-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP