replicas: 1
imageName: priobike-graphhopper-drn
deploymentName: priobike-graphhopper-drn-deployment
containerName: priobike-graphhopper-drn-container
serviceName: priobike-graphhopper-drn-service
labels:
  app: priobike-graphhopper-drn-app
