replicas: 1
imageName: priobike-sg-selector-hamburg
deploymentName: priobike-sg-selector-deployment
containerName: priobike-sg-selector-container
serviceName: priobike-sg-selector-service
labels:
  app: priobike-sg-selector-app
