apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
data:
  HOST_URL: |-
    http://
    {{- .Values.originServiceName -}}
    .
    {{- (.Values.global).namespace | default .Values.namespace | required "A valid .Values.namespace or .Values.global.namespace entry is required!" -}}
    .svc.cluster.local:
    {{- .Values.originServicePort }}
  SUCCESS_STORE_TIME: {{ .Values.successStoreTime }}
  NOT_FOUND_STORE_TIME: {{ .Values.notFoundStoreTime }}
  RESOLVER_IP: {{ .Values.resolverIp }}
