apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.manager.secretName }}
data:
  WORKER_BASIC_AUTH_USER: {{ required "A valid .Values.worker.basicAuthUser entry is required!" .Values.worker.basicAuthUser | b64enc }}
  WORKER_BASIC_AUTH_PASS: {{ required "A valid .Values.worker.basicAuthPass entry is required!" .Values.worker.basicAuthPass | b64enc }}
  