apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  selector:
    app: {{ .Values.labels.app }}
  ports:
    - protocol: TCP
      port: 8989
      targetPort: 8989
  type: ClusterIP