apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.manager.secretName }}
data:
  DJANGO_SUPERUSER_PASSWORD: {{ required "A valid .Values.manager.djangoSuperuserPassword entry is required!" .Values.manager.djangoSuperuserPassword | b64enc }}
  DJANGO_KEY: {{ required "A valid .Values.djangoKey entry is required!" .Values.djangoKey | b64enc }}
  SYNC_KEY: {{ required "A valid .Values.syncKey entry is required!" .Values.syncKey | b64enc }}
