apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.manager.volumeClaimName }}
spec:
  storageClassName: {{ .Values.manager.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.manager.storageSize }}
