apiVersion: v1
kind: Service
metadata:
  name: priobike-mqtt-service
spec:
  selector:
    app: priobike-mqtt-app
  ports:
    - protocol: TCP
      port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}
      nodePort: {{ .Values.nodePort }}
  type: NodePort