apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: priobike-shlink-postgres-volume-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi