apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: priobike-shlink-postgres-volume-claim
spec:
  selector:
    app: priobike-shlink-postgres-app
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi