apiVersion: v1
kind: PersistentVolume
metadata:
  name: priobike-shlink-postgres-volume
spec:
  selector:
    app: priobike-shlink-postgres-app
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/lib/postgresql/data