apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: priobike-shlink-postgres-statefulset
spec:
  serviceName: priobike-shlink-postgres-service
  replicas: 1
  selector: 
    matchLabels:
      app: priobike-shlink-postgres-app
  template:
    metadata:
      labels:
        app: priobike-shlink-postgres-app
    spec:
      containers:
      - name: priobike-shlink-postgres-container
        image: postgres:16.3
        envFrom:
        - configMapRef:
            name: priobike-shlink-postgres-config
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: priobike-shlink-postgres-volume-claim
